In [2]:
import torch

device = torch.device('mps')
device

device(type='mps')

In [7]:
tmp = torch.tensor([[1,2], [3,4]], device=device)
tmp = tmp.reshape(4,1)
display(tmp)

tmp = torch.tensor([[1,2], [3,4]], device=device)
tmp = tmp.reshape(-1)
display(tmp)

tmp = torch.tensor([[1,2], [3,4]], device=device)
tmp = tmp.reshape(1,-1)
display(tmp)

tmp = torch.tensor([[1,2], [3,4]], device=device)
tmp = tmp.reshape(-1,1)
display(tmp)

tmp = torch.tensor([[1,2], [3,4]], device=device)
tmp = tmp.reshape(1,1,-1)
display(tmp)



tensor([[1],
        [2],
        [3],
        [4]], device='mps:0')

tensor([1, 2, 3, 4], device='mps:0')

tensor([[1, 2, 3, 4]], device='mps:0')

tensor([[1],
        [2],
        [3],
        [4]], device='mps:0')

tensor([[[1, 2, 3, 4]]], device='mps:0')