In [1]:
import numpy as np


## numpy 배열

In [2]:
arr = np.array([[[1,2,3],],[[1,2,3]],[[1,2,3]]])
arr.shape

(3, 1, 3)

In [15]:
arr.reshape(9, -1)

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3],
       [1],
       [2],
       [3]])

In [19]:
np.array([1,2,3]) + 3

array([4, 5, 6])

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.stack((a,b), axis=1))
print(np.concatenate((a,b), axis=0))

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
