# The Simple Gridworld Problem

In [104]:
import numpy as np

P = np.array([
    # up
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],
    
    # down
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],
    
    # left
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # right
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]], dtype='float32')

P.shape

(4, 12, 12)

In [105]:
P = P.transpose(1, 0, 2)

In [106]:
P.shape

(12, 4, 12)

In [107]:
R = np.array([
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 0], # up
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0], # down
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0], # left
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0]], #right
    dtype='float32')

In [108]:
R.shape

(4, 12)

In [109]:
R = R.transpose()

In [110]:
R.shape

(12, 4)

In [111]:
pi = np.ones((12, 4), dtype='float32') * 0.25
pi

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]], dtype=float32)

In [112]:
pi.shape

(12, 4)

### In summary,

In [113]:
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 12), dtype='float32')
    
    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ), 
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))
    
    return V[maxiter-1]

def policy_upd(P, R, v):
    print(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )))
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((12, 4), dtype='float32')
    pi[range(12), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((12, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)
    
print(pi)

[[-2.4998531 -2.4993482 -2.4998531 -2.4999666]
 [-2.4999666 -2.4999666 -2.4998531 -2.499992 ]
 [-2.499992  -2.499992  -2.4999666 -2.4999976]
 [-2.4999976 -2.4999976 -2.499992  -2.4999976]
 [-2.4998531 -2.497106  -2.4993482 -2.4993482]
 [-2.4993482 -2.492127  -2.497106  -2.492127 ]
 [-2.492127  -2.4661531 -2.497106  -2.492127 ]
 [-2.497106  -2.492127  -2.492127  -2.4661531]
 [-2.492127  -2.4661531 -2.492127  -2.3239489]
 [-2.3239489 -2.3239489 -2.4661531 -1.7122748]
 [ 1.        -1.7122748 -2.3239489 -1.7122748]
 [ 0.         0.         0.         0.       ]]
[[-2.4020224  -2.336704   -2.4020224  -2.4412136 ]
 [-2.4412136  -2.4412136  -2.4020224  -2.4647284 ]
 [-2.4647284  -2.4647284  -2.4412136  -2.478837  ]
 [-2.478837   -2.478837   -2.4647284  -2.478837  ]
 [-2.4020224  -2.22784    -2.336704   -2.336704  ]
 [-2.336704   -2.0464     -2.22784    -2.0464    ]
 [-2.0464     -1.744      -2.22784    -2.0464    ]
 [-2.22784    -2.0464     -2.0464     -1.744     ]
 [-2.0464     -1.744      -